### ISSUE TITLE
unable to connect to api

### ISSUE THREAD

**Issue by smitdol** [segler-alex/RadioDroid#1247]
since a couple of days the radiodroid 0.83 nor 0.84 app is able to connect to radio browser server and not able to play any station

user agent string (chrome browser) of phone running radiodroid (according to https://dnschecker.org/user-agent-info.php)
Mozilla/5.0 (linux; Android 4.4.2; ARCHOS 40C TIv2 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.135 Mobile Safari/537.36

this old phone is only and solely used for/as radiodroid client.

certificates for letsencrypt (ISRG Root X1, E5, E6, R10, R11, R3) have been manually installed on this phone.

phone/chrome is unable to show www.radio-browser.info, but is able to show 'Community Radio Station Index' on all.api.radio-browser.info.
de2.api.radio-browser.info shows 'Community Radio Station Index'
nl1.api.radio-browser.info shows 'not available' in chrome,  

can it be that this old phone is disallowed from contacting the api?

can I change/select somewhere in radiodroid which api to query?

**Comment by apuser31** [comment]
I am having the same issue: Kitkat 4.4.2, installed DigiCert Global Root G2, ISRG Root X1, ISRG Root X2, and Let's Encrypt R3 certificates -- but two days ago I started getting "Could not connect to station" trying any station.

**Comment by smitdol** [comment]
I duplicated this issue on https://gitlab.com/radiobrowser/radiobrowser-api-rust/-/issues/230, because of a recent change in there, which might be unrelated

**Comment by holdit** [comment]
Can confirm that Radio Droid isn't working. Xiaomi, Samsung and Motorola devices, running Android 14 and 15, v0.86 from F-Droid.

Radiolise is also taking 3 or 4 minutes for a station to start playing.

**Comment by Wikinaut** [comment]
The central server appears to be down or unreachable.

Same issue here.

**Comment by c-e-github** [comment]
Same issue here. (Sony Xperia III, Android 13, RadioDroid 0.86)

**Comment by puppykickr** [comment]
the app doesnt work, but at least you can tap the home icon on the station you want and listen through a browser.

seems to be the best way anyway, because none of this type app seems as reliable as just going to the stations site on a good browser

**Comment by STPKITT** [comment]
Wow, until now I thought this great app only depended on the server for searching stations. That's a pretty bad design then. Hopefully this issue can be resolved quickly and for the long term the dependecy on the server for everything should be axed. Not even importing a playlist file exported from another device running RadioDroid currently works.

**Comment by lunctis-viribus** [comment]
The app is indeed broken since 2 days. I'm using v0.86 from F-Droid.

The connection/API to all.api.radio-browser.info/443 seems broken/not working anymore.

Also reinstalling or downgrading to v0.84 didn't help. I even lost my Favorites unfortunately.

**Comment by Meserias** [comment]
I'm having the same issue. Yesterday, out of the blue, the application stopped playing any streams. I have already tried the usual troubleshooting steps: restarting the phone, changing networks (triple-checking that the station is working as expected on the same phone with diffrent app), using cellular data from three different providers, clearing the app data, and finally, completely reinstalling the app.

I also tried using a couple of other phones from different brands.
I have switched to RadioGarden for now .....

**Comment by morckx** [comment]
Should be working again (not thanks to me).

**Comment by wunderfisch** [comment]
Sometimes you realize just after a problem that you enjoyed a FOSS app that has been maintained by volunteers (and often one main maintainer) in their free time for many years. That's the moment to remember to say thank you! Therefore: thanks @segler-alex and @morckx (and others(?)) for starting, open sourcing and maintaining this project while most of the tech sector is highly monetized!

**Comment by smitdol** [comment]
works again, thank you all for fixing it.

**Comment by Wikinaut** [comment]
confirmed: it is working again

**Comment by apuser31** [comment]
But still broken for me, and not permitted to re-open this issue (#1247) -- opened new (same) issue #1249.  Thanks.

**Comment by smitdol** [comment]
Have to reopen this issue....

It was working last Sunday, but not anymore since then.
"could not connect to radio browser server" 
"importing favorites from playlist" fails (loaded 0 stations)

I can browse www.radio-browser.info (albeit does not render on this old device) and all.api.radio-browser.info (which does render) from same device, so certificates looks correctly installed.

tried versions 0.83, 0.84, 0.86 and free-debog-dev-0.84, but none works.

**Comment by STPKITT** [comment]
I experience the same. This issue isn't solved and should be re-opened by anyone who is blessed with the permission to do so.

**Comment by apuser31** [comment]
End of an era?  Evidently this issue at least, perhaps the app itself, is abandoned.  Well, can't complain I guess -- it worked very well (mostly) for a long time and I have to appreciate the efforts of the creator and of everyone who contributed ideas, suggestions and troubleshooting tips over the years.  It's disappointing to have to look for a new (or old?) app that will still work -- any suggestions welcome! -- but there it is.  I will miss RadioDroid.  Thanks everyone for helping it last this long.

**Comment by smitdol** [comment]
for what is worth: I switched to an android 10 device, and with that radiodroid (0.86) (still) works

**Comment by STPKITT** [comment]
I didn't switch my Android, but the app is currently working fine. Maybe it's just sporadic server issue. The sad thing is that the app as it seems is dependent on more servers than necessary.

**Comment by apuser31** [comment]
Sadly, doesn't work for me anymore, and I haven't a clue how to enable it.  Buying a new phone (especially just to use a no-longer-supported app -- for a little while longer) isn't really an option.

**Comment by STPKITT** [comment]
@apuser31 Try stopping the app, then deleting it's cache and then try the app again. If you don't care about your data in the app getting deleted you could also try and go one step further by fully deinstalling the app and reinstalling it then.
